CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(25) PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS posts (
    id VARCHAR(25) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    author_id VARCHAR(25) NOT NULL REFERENCES users(id)  ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS comments (
    id VARCHAR(25) PRIMARY KEY,
    post_id VARCHAR(25) NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    author_id VARCHAR(25) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    parent_id VARCHAR(25) REFERENCES comments(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    hasChildren BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);